<a href="https://colab.research.google.com/github/jaimitgandhi/iNeuron/blob/master/Copy_of_Assignment_3_Python_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [0]:
def divide(a,b):
  return a/b

try:
  a=5
  b=0
  divide(a,b)
except ZeroDivisionError as zero:
  print("Divide by zero")

Divide by zero


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [0]:
subjects = ["Americabs","Indians"]
verbs = ["play","watch"]
objects = ["Baseball","Cricket"]

for sub in subjects:
  for verb in verbs:
    for obj in objects:
      print(sub + " "+ verb + " "+ obj)

Americabs play Baseball
Americabs play Cricket
Americabs watch Baseball
Americabs watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [0]:
import numpy as np
def vandermode(x,N):
    output = np.vander(x,N)
    print(output)

x = np.array([1,2,3,4])
N=3
vandermode(x,N)


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


In [0]:
def custom_vandermode(x,N):
    output = np.column_stack([x**(N-1-i) for i in range(N)])
    print(output)
  
x = np.array([5,6,7,8])
N=4
custom_vandermode(x,N)

[[125  25   5   1]
 [216  36   6   1]
 [343  49   7   1]
 [512  64   8   1]]
